### ISSUE TITLE
NO I CANT I NEED TUTORIAL PLEASE

### ISSUE THREAD

**Issue by SalChroma** [CUPZYY/Backdoor-Machine#10]

**Comment by SalChroma** [comment]
PLS
MAKE A TUTORIAl

**Comment by HerraVp** [comment]
![obama](https://user-images.githubusercontent.com/59320967/124496239-d6606400-ddc1-11eb-9c27-a3d979a3141b.gif)

**Comment by SalChroma** [comment]
:(

**Comment by SalChroma** [comment]
baracke obamane

**Comment by SalChroma** [comment]
![](https://user-images.githubusercontent.com/59320967/124496239-d6606400-ddc1-11eb-9c27-a3d979a3141b.gif)

**Comment by CUPZYY** [comment]
@SalChroma 
No, I will not make a tutorial. Just google the bits of the documentation you don't understand
