### ISSUE TITLE
Paste the webhook url into the variable at line 29.

### ISSUE THREAD

**Issue by SalChroma** [CUPZYY/Backdoor-Machine#11]
i doesnt understand how to make the exe thing

**Comment by SalChroma** [comment]
howww

**Comment by SalChroma** [comment]
Paste the webhook url into the variable at line 29.
Run the code or something.
dafug

**Comment by SalChroma** [comment]
where is line 29
-+

**Comment by SalChroma** [comment]
![image](https://user-images.githubusercontent.com/83649098/124499984-243c9280-dde9-11eb-80e2-e5c4dd93f37f.png)

**Comment by SalChroma** [comment]
@CUPZYY

**Comment by CUPZYY** [comment]
you gotta have either chrome or brave browser installed

**Comment by SalChroma** [comment]
i have chrome

**Comment by SalChroma** [comment]
@CUPZYY

**Comment by SalChroma** [comment]
![image](https://user-images.githubusercontent.com/83649098/124503283-6c5eb380-ddef-11eb-98bf-ec9b4084bd44.png)

**Comment by SalChroma** [comment]
**BRO**

**Comment by CUPZYY** [comment]
redownload the repo, you have probably modified something

**Comment by CUPZYY** [comment]
> where is line 29
> -+
line 29 is at line 29
