### ISSUE TITLE
On  execution It doesn't work, doesn't send anything to my webhook

### ISSUE THREAD

**Issue by MaxwellGLT** [CUPZYY/Backdoor-Machine#12]
My webhook is valid and didn't change anything except the webhook variable .

**Comment by CUPZYY** [comment]
run it in idle and tell me the error message

**Comment by savio2311** [comment]
i am facing the same issue not receiving any messages on discord

**Comment by CUPZYY** [comment]
as I said, run it in Python IDLE and tell me what it says
