### ISSUE TITLE
Pls help me bros

### ISSUE THREAD

**Issue by Richtine** [CUPZYY/Backdoor-Machine#16]
Anonfiles.com is banned in my area. Can I use another site? How do I use it?

**Comment by Richtine** [comment]
@CUPZYY  @opabravo

**Comment by LudovicoSforza** [comment]
use VPN?

**Comment by Richtine** [comment]
so does the victim need to use vpn?

**Comment by CUPZYY** [comment]
As @LudovicoSforza said, your only choice here is to use a vpn. If the victim is outside of your country, it will still work
