### ISSUE TITLE
WARNING: Hidden import "pkg_resources.markers" not found!

### ISSUE THREAD

**Issue by Jerrynh770** [CUPZYY/Backdoor-Machine#5]

**Comment by CUPZYY** [comment]
Does this issue prevent the program from running at all?

**Comment by Jerrynh770** [comment]
no

**Comment by CUPZYY** [comment]
> no

so why did you make this issue?

**Comment by Jerrynh770** [comment]
because i cant call it up on discord. i can see it is runing but nothing show up on my discord

**Comment by CUPZYY** [comment]
> because i cant call it up on discord. i can see it is runing but nothing show up on my discord
> 
> 
> 
> 

Read readme.md to find out how to use
