### ISSUE TITLE
build.py does nothing?

### ISSUE THREAD

**Issue by pkaas** [CUPZYY/Backdoor-Machine#6]
Whenever I open build.py, it opens up, shows no text and then immediately closes out. Why?

**Comment by CUPZYY** [comment]
Run it in IDLE and tell me what it says

**Comment by pkaas** [comment]
> Run it in IDLE and tell me what it says

nothing happens, it just says this

import subprocess

subprocess.call(
    "pyinstaller --noconfirm --onefile --windowed --add-data \"brave.py;.\" --add-data \"chrome.py;.\" --add-data \"encryption.py;.\" --add-data \"README.md;.\" --clean --hidden-import \"win32api\" \"main.py\"",
    shell=True)

**Comment by CUPZYY** [comment]
> > Run it in IDLE and tell me what it says
> 
> nothing happens, it just says this
> 
> import subprocess
> 
> subprocess.call(
> "pyinstaller --noconfirm --onefile --windowed --add-data "brave.py;." --add-data "chrome.py;." --add-data "encryption.py;." --add-data "README.md;." --clean --hidden-import "win32api" "main.py"",
> shell=True)

**Run** it in IDLE.

**Comment by pkaas** [comment]
i ran it and it created a dist, build and __pycache__. whenever i go into the dist and open the .exe, nothing sends to the server.

**Comment by CUPZYY** [comment]
> i ran it and it created a dist, build and **pycache**. whenever i go into the dist and open the .exe, nothing sends to the server.

are you sure the webhook url is correct?

**Comment by pkaas** [comment]
yep, i made a new webhook to make sure, saved it, ran it in IDLE again, opened the .exe and still nothing sent to the server.

**Comment by CUPZYY** [comment]
I have seen other people have this issue. Probably an issue with pycryptodome. There is nothing I can do about it atm but you can try reinstalling pycryptodome.

**Comment by pkaas** [comment]
i figured out how to get it to work, but now how do i get the decryption part to work? everytime i open it, it closes. i tried running with IDLE but nothing works from there.

**Comment by pkaas** [comment]
nevermind i figured out it was decrypt and not encryption. thank you for this!
