### ISSUE TITLE
build

### ISSUE THREAD

**Issue by AmpPy** [CUPZYY/Backdoor-Machine#7]
build broken

**Comment by CUPZYY** [comment]
give more information

**Comment by AmpPy** [comment]
> give more information

when i run build.py it doesnt work, all it does it open for 1s then close, i've tried in idle but same thing.

**Comment by CUPZYY** [comment]
no error messages when you run it in idle?

**Comment by AmpPy** [comment]
nope

**Comment by AmpPy** [comment]
nope

**Comment by CUPZYY** [comment]
> nope

try reinstalling pyinstaller
